Plugin secure connection support
JetBrains/projector-server pull request #106
Opened 2021-12-16 10:48 UTC by IKrukov-HORIS

- HTTPs connection support with autogenerated certificate
- plugin settings page added

2022-01-12 11:23 UTC, SerVB commented
Please request my review when it's not a draft

2022-02-09 15:34 UTC, SerVB requested changes
Thank you very much, I've checked, it works. Please resolve warnings from Qodana for the changed lines.

Also, I've collected some problems that are mostly UI/UX related:

![image](https://user-images.githubusercontent.com/20105593/153227581-e23efd85-3302-4f01-98e1-f5ab2490ee43.png)

1. When opening the More Settings window, options aren't synchronized with the previous window. When exiting from More Settings, options are passed to the previous window (both if we click OK or Cancel). To reproduce: generate a random password in the first window, open More Settings (newly generated password isn't applied), close More Settings (newly generated password is reset).
2. "Use names in URLs" – this checkbox affects only the shown invitation links, right? Then let's move it to that section to make it clearer.
3. Can we maybe reuse the Connections panel in both windows? For now, it's reused too, but it looks inconsistent. Also, we don't have this beautiful panel header line in the first panel, maybe we can add it there. But the header text itself is clearer in the first panel, "Listen on".
4. Let's move "start automatically..." and "require confirmation..." checkboxes to the bottom (in a new section like "Misc") – this will make the "Listen on" settings group the first group in both windows which can be more intuitive for a user.
5. (probably it was even before this PR, but we can resolve it now) Links (RW and RO) aren't aligned. We can align them, for example, on the right, like we align textfields for passwords.
6. Let's use the same header line for "Invitation links" too.
7. It's cool that we can enable and disable HTTPS when Projector is stopped and then start it with the changed protocol. However, to make this "Use HTTPS" checkbox active after stopping, I have to reopen the config window.

2022-02-10 15:05 UTC, IKrukov-HORIS commented on projector-plugin/CHANGELOG.md
> +
Fixed

2022-02-10 15:05 UTC, IKrukov-HORIS commented on projector-plugin/src/main/kotlin/org/jetbrains/projector/plugin/ui/SessionDialog.kt
> +      return urlHostsList.selected?.address ?: ""
Thank you for catching this, fixed.

2022-02-15 12:41 UTC, SerVB approved these changes
Only minor comments, feel free to merge

2022-02-15 12:41 UTC, SerVB commented on projector-plugin/src/main/kotlin/org/jetbrains/projector/plugin/Utils.kt
> +}
Was before this PR, but can be improved now:

```suggestion
fun generatePassword(): String {
  val charPool = ('a'..'z') + ('A'..'Z') + ('0'..'9')
  return generateSequence { charPool.random() }
    .take(RANDOM_PASSWORD_LEN)
    .joinToString("")
}
```

2022-02-15 12:41 UTC, SerVB commented on projector-plugin/src/main/kotlin/org/jetbrains/projector/plugin/ProjectorService.kt
> +    setSystemProperty(ProjectorServer.ENABLE_CONNECTION_CONFIRMATION, if (config.confirmConnection) "true" else "false")
Was before this PR but can be improved now (here and in other places):

```suggestion
    setSystemProperty(ProjectorServer.ENABLE_CONNECTION_CONFIRMATION, config.confirmConnection.toString())
```

2022-02-15 13:07 UTC, merged