Show notification about unsupported copying in insecure context in Electron
JetBrains/projector-server pull request #108
Opened 2021-12-21 08:25 UTC by ARTI1208

2022-01-25 17:22 UTC, ARTI1208 commented
Dunno why jitpack rejects 8-digit commit hash, so used 10-digit for now. Hope situation will change after client commits will go to master

2022-02-03 11:14 UTC, SerVB requested changes

2022-02-03 11:14 UTC, SerVB commented on projector-server/src/main/kotlin/org/jetbrains/projector/server/ProjectorServer.kt
> +        val notification = Notification("ProjectorClient", message.title, message.message, intellijNotificationType)
This line is marked as red in IDEA: `Cannot resolve notification group id 'ProjectorClient'`. Maybe we should suppress this or solve it in some other way.

Also, what happens here if we run Projector with a plain Swing app (not IntelliJ-based)? Probably we should surround these lines that use IntelliJ classes to `runWhenIdeIsInitialized`?

2022-02-03 11:14 UTC, SerVB commented on gradle.properties
> +projectorClientVersion=a5fb8893df
Well, I would recommend researching why it happened. Probably it was a temporary problem on JitPack and the build should be rerun there. Please ask for help if it's still unclear

2022-03-15 08:34 UTC, merged